# Usa la imagen oficial de Prometheus
FROM prom/prometheus

# Copia el archivo de configuración de Prometheus al contenedor
COPY prometheus.yaml /etc/prometheus/prometheus.yaml

# Expone el puerto necesario
EXPOSE 9090