apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/common
  - ../../base/exporter
  # - ../../base/grafana
  # - ../../base/prometheus

namespace: solar-panel-monitoring